// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JUI7dULtc96dcv9RwYb7N2v4Is6fxH0',
    appId: '1:129116157854:web:bac96fafe5824fcf1d488f',
    messagingSenderId: '129116157854',
    projectId: 'chatapptut-a54d2',
    authDomain: 'chatapptut-a54d2.firebaseapp.com',
    storageBucket: 'chatapptut-a54d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmF3TH3SuzUWIrEWyKWRGP-y9wyNhRM1c',
    appId: '1:129116157854:android:9a713e590f84637b1d488f',
    messagingSenderId: '129116157854',
    projectId: 'chatapptut-a54d2',
    storageBucket: 'chatapptut-a54d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjag15N6LqF7jp8eCMsCxivIsMHmwVd4',
    appId: '1:129116157854:ios:3b8643b90d1ef5541d488f',
    messagingSenderId: '129116157854',
    projectId: 'chatapptut-a54d2',
    storageBucket: 'chatapptut-a54d2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxjag15N6LqF7jp8eCMsCxivIsMHmwVd4',
    appId: '1:129116157854:ios:3b8643b90d1ef5541d488f',
    messagingSenderId: '129116157854',
    projectId: 'chatapptut-a54d2',
    storageBucket: 'chatapptut-a54d2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7JUI7dULtc96dcv9RwYb7N2v4Is6fxH0',
    appId: '1:129116157854:web:d2c3fc126661a9a81d488f',
    messagingSenderId: '129116157854',
    projectId: 'chatapptut-a54d2',
    authDomain: 'chatapptut-a54d2.firebaseapp.com',
    storageBucket: 'chatapptut-a54d2.appspot.com',
  );
}
